/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#0c0f0e",
        "primary-dim": "#435657",
        "surface-container-high": "#e3e9e8",
        "tertiary": "#5a615b",
        "on-secondary-container": "#485452",
        "on-primary-fixed": "#304344",
        "inverse-on-surface": "#9b9d9d",
        "surface-bright": "#f9f9f8",
        "tertiary-container": "#eff5ee",
        "secondary": "#55625f",
        "outline-variant": "#abb4b3",
        "surface-dim": "#d2dcdb",
        "on-error": "#fff7f6",
        "surface-container-highest": "#dce4e3",
        "on-tertiary": "#f5fbf3",
        "on-primary-container": "#425556",
        "surface-variant": "#dce4e3",
        "secondary-fixed-dim": "#cad7d4",
        "tertiary-fixed-dim": "#e1e7e0",
        "on-primary": "#e7fcfd",
        "inverse-primary": "#e8fdfe",
        "tertiary-fixed": "#eff5ee",
        "surface-tint": "#4f6263",
        "on-tertiary-container": "#575d58",
        "on-background": "#2c3433",
        "outline": "#747c7c",
        "error": "#9f403d",
        "on-secondary-fixed": "#36423f",
        "on-tertiary-fixed-variant": "#616862",
        "primary-container": "#d2e6e7",
        "on-surface-variant": "#586160",
        "primary-fixed": "#d2e6e7",
        "on-surface": "#2c3433",
        "error-dim": "#4e0309",
        "on-error-container": "#752121",
        "secondary-dim": "#495653",
        "on-secondary": "#eefcf8",
        "primary-fixed-dim": "#c4d8d9",
        "tertiary-dim": "#4e554f",
        "on-primary-fixed-variant": "#4c5f60",
        "on-tertiary-fixed": "#454b46",
        "background": "#f9f9f8",
        "primary": "#4f6263",
        "error-container": "#fe8983",
        "surface-container-low": "#f1f4f3",
        "secondary-container": "#d8e5e2",
        "surface-container": "#eaefee",
        "on-secondary-fixed-variant": "#525e5b",
        "secondary-fixed": "#d8e5e2",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f8"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
